<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_WeightCalc" Id="{2b206187-600e-4336-b998-08e78e06b406}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_WeightCalc : real
VAR_INPUT
	dia			: REAL;
	height 		: REAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_WeightCalc := dia*pi*height;]]></ST>
    </Implementation>
    <LineIds Name="F_WeightCalc">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>